### ISSUE TITLE
turn div into image

### ISSUE THREAD

**Issue by maxyeo** [maxyeo/catchat#5]

**Comment by maxyeo** [comment]
https://html2canvas.hertzen.com/

**Comment by maxyeo** [comment]
![image](https://cloud.githubusercontent.com/assets/5505326/12067220/3aaeee72-afc4-11e5-90c9-8e66f7f7defb.png)
![image](https://cloud.githubusercontent.com/assets/5505326/12067223/425fd37a-afc4-11e5-92d5-d235a198dc76.png)
not quite working, going to read up on canvas and render it myself

**Comment by WilliamChiu** [comment]
ended up using chrome's captureVisibleTab. think I've got a working example

**Comment by maxyeo** [comment]
awesome, it works! good work Billy!
